function convertObjToWrl(objData) {
  const materials = {};
  const materialMatches = objData.match(/newmtl[\s\S]*?endmtl/g) || [];
  for (const match of materialMatches) {
    const material = {};
    let materialId = "";
    for (const line of match.split(/\r?\n/)) {
      if (line.startsWith("newmtl")) {
        materialId = line.split(" ")[1];
      } else if (line.startsWith("Ka")) {
        material.ambient = line.split(" ").slice(1);
      } else if (line.startsWith("Kd")) {
        material.diffuse = line.split(" ").slice(1);
      } else if (line.startsWith("Ks")) {
        material.specular = line.split(" ").slice(1);
      } else if (line.startsWith("d")) {
        material.transparency = line.split(" ").slice(1);
      }
    }
    materials[materialId] = material;
  }

  const vertices = (objData.match(/^v\s+.*$/gm) || []).map((line) => {
    const coords = line
      .replace(/^v\s+/, "")
      .trim()
      .split(/\s+/)
      .map((value) => (Number(value) / 2.54).toFixed(4));
    return coords.join(" ");
  });

  let rawWrl =
    "#VRML V2.0 utf8\n# 3D model generated by easy EDA downloader\n";

  const shapes = objData.split("usemtl").slice(1);
  for (const shape of shapes) {
    const lines = shape.split(/\r?\n/).filter(Boolean);
    if (!lines.length) {
      continue;
    }
    const material = materials[lines[0].replace(/\s+/g, "")] || {};
    const coordIndex = [];
    const points = [];
    const linkMap = new Map();
    let indexCounter = 0;

    for (const line of lines.slice(1)) {
      if (!line.startsWith("f ")) {
        continue;
      }
      const face = line
        .replace(/^f\s+/, "")
        .replace(/\/\//g, "/")
        .split(/\s+/)
        .map((part) => parseInt(part.split("/")[0], 10));

      const faceIndex = [];
      for (const idx of face) {
        if (!linkMap.has(idx)) {
          linkMap.set(idx, indexCounter);
          faceIndex.push(String(indexCounter));
          points.push(vertices[idx - 1]);
          indexCounter += 1;
        } else {
          faceIndex.push(String(linkMap.get(idx)));
        }
      }
      faceIndex.push("-1");
      coordIndex.push(faceIndex.join(" ") + ",");
    }
    if (points.length) {
      points.splice(points.length - 1, 0, points[points.length - 1]);
    }

    rawWrl += `
Shape{
    appearance Appearance {
        material  Material {
            diffuseColor ${(material.diffuse || []).join(" ")}
            specularColor ${(material.specular || []).join(" ")}
            ambientIntensity 0.2
            transparency 0
            shininess 0.5
        }
    }
    geometry IndexedFaceSet {
        ccw TRUE
        solid FALSE
        coord DEF co Coordinate {
            point [
                ${points.join(", ")}
            ]
        }
        coordIndex [
            ${coordIndex.join("")}
        ]
    }
}`;
  }

  return rawWrl;
}

export { convertObjToWrl };

/*
######################################################################################################################


                                        AAAAAAAA
                                      AAAA    AAAAA              AAAAAAAA
                                    AAA          AAA           AAAA    AAA
                                    AA            AA          AAA       AAA
                                    AA            AAAAAAAAAA  AAA       AAAAAAAAAA
                                    AAA                  AAA  AAA               AA
                                     AAA                AAA    AAAAA            AA
                                      AAAAA            AAA        AAA           AA
                                         AAA          AAA                       AA
                                         AAA         AAA                        AA
                                         AA         AAA                         AA
                                         AA        AAA                          AA
                                        AAA       AAAAAAAAA                     AA
                                        AAA       AAAAAAAAA                     AA
                                        AA                   AAAAAAAAAAAAAA     AA
                                        AA  AAAAAAAAAAAAAAAAAAAAAAAA    AAAAAAA AA
                                       AAAAAAAAAAA                           AA AA
                                                                           AAA  AA
                                                                         AAAA   AA
                                                                      AAAA      AA
                                                                   AAAAA        AA
                                                               AAAAA            AA
                                                            AAAAA               AA
                                                        AAAAAA                  AA
                                                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA


######################################################################################################################

                                                Copyright (c) JoeShade
                              Licensed under the GNU Affero General Public License v3.0

######################################################################################################################

                                        +44 (0) 7356 042702 | joe@jshade.co.uk

######################################################################################################################
*/
